# Generated by Django 2.2.2 on 2019-06-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_criterion_department_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='plant.Department'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='criterion',
            unique_together={('name', 'department')},
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
