# Generated by Django 2.2.2 on 2019-07-03 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='department',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='month',
            field=models.SmallIntegerField(default=7, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='year',
            field=models.SmallIntegerField(default=2019, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='checked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_evaluations', to='plant.Criterion'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_evaluations', to='plant.Unit'),
        ),
    ]
