# Generated by Django 2.2.2 on 2019-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_auto_20190703_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='month',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='year',
            field=models.SmallIntegerField(),
        ),
    ]
