# Generated by Django 2.2.2 on 2019-07-05 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_auto_20190703_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_evaluations', to='plant.Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='checked',
            field=models.BooleanField(),
        ),
    ]
