# Generated by Django 2.2.2 on 2019-07-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_auto_20190705_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='date',
            field=models.DateField(default='2019-7-1'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('date', 'unit')},
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='month',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='year',
        ),
    ]
