# Generated by Django 2.2.2 on 2019-07-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_auto_20190706_0856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('date', 'criterion')},
        ),
    ]
