# Generated by Django 2.2.2 on 2019-07-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_auto_20190706_0903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together=set(),
        ),
    ]
