# Generated by Django 2.2.2 on 2019-07-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_auto_20190706_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='date',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='month',
            field=models.SmallIntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='year',
            field=models.SmallIntegerField(default=2019),
            preserve_default=False,
        ),
    ]
