# Generated by Django 2.2.2 on 2019-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0011_auto_20190706_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='suggested_solution',
            field=models.TextField(null=True),
        ),
    ]
