# Generated by Django 2.2.2 on 2019-07-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0012_criterion_suggested_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
