# Generated by Django 2.2.2 on 2019-07-11 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0013_auto_20190711_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterion',
            name='suggested_solution',
        ),
    ]
